---
- name: something
  hosts: all
  become: yes
  tasks:
  - name: make filesystem
    filesystem:
      fstype: xfs
      force: yes
      dev: "{{ item.0 }}"
      opts: -L "disk{{ item.1 }}"
    with_together:
      - [ '/dev/vdc1', '/dev/vdd1', '/dev/vde1', '/dev/vdf1' ]
      - [ 1, 2, 3, 4 ]

      
